export const DEFAULT_CONFIG = [
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'superscript',
  'subscript',
];

export const FONT_SIZE_OPTIONS = [
  { label: '8', value: '8px' },
  { label: '9', value: '9px' },
  { label: '10', value: '10px' },
  { label: '11', value: '11px' },
  { label: '12', value: '12px' },
  { label: '14', value: '14px' },
  { label: '16', value: '16px' },
  { label: '18', value: '18px' },
  { label: '20', value: '20px' },
  { label: '24', value: '24px' },
  { label: '28', value: '28px' },
  { label: '32', value: '32px' },
  { label: '36', value: '36px' },
  { label: '40', value: '40px' },
  { label: '48', value: '48px' },
  { label: '56', value: '56px' },
  { label: '64', value: '64px' },
  { label: '72', value: '72px' },
  { label: '80', value: '80px' },
  { label: '96', value: '96px' },
];
